### model
model_name_or_path: meta-llama/CodeLlama-7b-hf

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: math_multilingpot
template: llama2
cutoff_len: 1024
overwrite_cache: true

### output
output_dir: saves/multilingpot.codellama
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2e-5
num_train_epochs: 3
